\set ON_ERROR_STOP on
begin;
do $$
declare own public.users; other_user public.users; cleaner public.users; admin_user public.users;
 prop uuid; job uuid; room uuid:=gen_random_uuid(); result jsonb; notice text; count_events integer;
begin
 insert into public.users(clerk_user_id,role,display_name,onboarding_completed_at) values('activity-owner-'||gen_random_uuid(),'owner','Activity owner',now()) returning * into own;
 insert into public.users(clerk_user_id,role,display_name,onboarding_completed_at) values('activity-other-'||gen_random_uuid(),'owner','Other owner',now()) returning * into other_user;
 insert into public.users(clerk_user_id,role,display_name,onboarding_completed_at) values('activity-cleaner-'||gen_random_uuid(),'cleaner','Activity cleaner',now()) returning * into cleaner;
 insert into public.users(clerk_user_id,role,display_name,onboarding_completed_at) values('activity-admin-'||gen_random_uuid(),'admin','Activity admin',now()) returning * into admin_user;
 insert into public.properties(city_id,name,address,cleaning_config) values('00000000-0000-4000-8000-000000000001','Activity fixture','Synthetic address',jsonb_build_object('rooms',jsonb_build_array(jsonb_build_object('id',room,'type','bedrooms','label','Upstairs bedroom')))) returning id into prop;
 insert into public.property_owners values(prop,own.id);
 insert into public.jobs(property_id,checkout_date,start_at,end_at,timezone_snapshot,solo_rate_cents_snapshot) values(prop,current_date,(current_date+time '11:00') at time zone 'America/Detroit',(current_date+time '15:00') at time zone 'America/Detroit','America/Detroit',7500) returning id into job;
 insert into public.job_photos(job_id,uploader_id,category,room_id,object_path,state,bytes,mime) values(job,cleaner.id,'bedrooms',room,job::text||'/'||gen_random_uuid(),'ready',200,'image/png');
 insert into public.job_photos(job_id,uploader_id,category,object_path,state,bytes,mime) values(job,cleaner.id,'kitchen',job::text||'/'||gen_random_uuid(),'pending',200,'image/png');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',own.clerk_user_id)::text,true);
 if private.photo_access(job) then raise exception 'Owner sees unfinished photos';end if;
 update public.jobs set status='completed',completed_at=now(),completed_by=cleaner.id where id=job;
 update public.jobs set status='completed' where id=job;
 select count(*) into count_events from private.cleaning_activity_events where job_id=job;
 if count_events<>1 then raise exception 'Duplicate completion notice';end if;
 update public.properties set cleaning_config='{"rooms":[]}' where id=prop;
 result:=public.bloom_cleaning_activity(0,job);
 if result#>>'{items,0,photos,0,locationLabel}'<>'Upstairs bedroom' or (result#>>'{items,0,photoCount}')::integer<>1 then raise exception 'Room snapshot/ready-only photos failed';end if;
 if not private.photo_access(job) or private.photo_access(job,true) then raise exception 'Owner photo permissions failed';end if;
 select id into notice from private.inbox_items() where id='completion:'||job::text and href='/owner?view=activity&job='||job::text;
 if notice is null then raise exception 'Owner completion notice missing';end if;
 perform public.bloom_notification_dismiss(notice);
 if exists(select 1 from jsonb_array_elements(public.bloom_notification_inbox()->'items') x where x->>'id'=notice) then raise exception 'Dismiss failed';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',other_user.clerk_user_id)::text,true);
 if private.photo_access(job) then raise exception 'Cross owner photos exposed';end if;
 begin perform public.bloom_cleaning_activity(0,job);raise exception 'Cross owner activity exposed';exception when others then if sqlerrm<>'NOT_FOUND' then raise;end if;end;
 if exists(select 1 from private.inbox_items() where id='completion:'||job::text) then raise exception 'Cross owner notification exposed';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',cleaner.clerk_user_id)::text,true);
 begin perform public.bloom_cleaning_activity();raise exception 'Cleaner accessed activity';exception when others then if sqlerrm<>'FORBIDDEN' then raise;end if;end;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',admin_user.clerk_user_id)::text,true);
 if not exists(select 1 from private.inbox_items() where id='completion:'||job::text and href='/admin?view=activity&job='||job::text) then raise exception 'Admin completion notice missing';end if;
 perform public.bloom_cleaning_activity(0,job);
 if has_table_privilege('authenticated','private.cleaning_activity_events','SELECT') then raise exception 'Event table exposed';end if;
 raise notice 'Activity: owner/admin access, cross-owner denial, cleaner denial, frozen room label, ready photos only, notification deduplication, deep links and dismissal passed.';
end $$;
rollback;
