'use client';
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import {Popover} from '@base-ui/react/popover';
import {request} from '../bloom/api';
import {ErrorNotice,Loading,useResource} from '../bloom/primitives';
type InboxPage={items:{id:string;body:string;href:string;dismissible:boolean}[];total:number};
export function NotificationInbox({cleaner=false}:{cleaner?:boolean}){
 const [open,setOpen]=useState(false),[offset,setOffset]=useState(0),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState<unknown>();
 const load=useCallback((signal:AbortSignal)=>request<InboxPage>(`/notifications?offset=${offset}`,{signal}),[offset]);const data=useResource(load,true);
 useEffect(()=>{const refresh=()=>data.reload();window.addEventListener('bloom:payouts-changed',refresh);window.addEventListener('focus',refresh);const timer=setInterval(()=>{if(document.visibilityState==='visible')refresh();},30000);return()=>{window.removeEventListener('bloom:payouts-changed',refresh);window.removeEventListener('focus',refresh);clearInterval(timer);};},[data.reload]);
 const count=data.data?.total??0;
 return <Popover.Root open={open} onOpenChange={value=>{setOpen(value);if(value)data.reload();}}><Popover.Trigger className="admin-inbox-trigger" aria-label={`Notifications${count?`, ${count} need attention`:''}`}><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></svg>{count>0&&<span>{count}</span>}</Popover.Trigger><Popover.Portal><Popover.Positioner sideOffset={10} align="end" collisionPadding={16} style={{zIndex:100}}><Popover.Popup className="admin-pricing-inbox"><Popover.Title>Notifications</Popover.Title>{cleaner&&<button className="bloom-inbox-settings" onClick={()=>{setOpen(false);window.dispatchEvent(new Event('bloom:notification-settings'));}}>Notification settings</button>}{data.loading?<Loading/>:data.error?<ErrorNotice error={data.error} retry={data.reload}/>:count>0?<><ul>{data.data?.items.map(item=><li key={item.id}><Link href={item.href} onClick={()=>setOpen(false)}>{item.body}<span>View details →</span></Link>{item.dismissible&&<button className="bloom-inbox-dismiss" disabled={busy!==null} aria-label={`Dismiss: ${item.body}`} onClick={async()=>{if(busy)return;setBusy(item.id);setError(undefined);try{await request('/notifications',{body:{id:item.id}});setOffset(0);data.reload();}catch(e){setError(e);}finally{setBusy(null);}}}>{busy===item.id?'Dismissing…':'Dismiss'}</button>}</li>)}</ul><nav className="bloom-inbox-pages" aria-label="Notification pages"><button disabled={offset===0} onClick={()=>setOffset(n=>Math.max(0,n-10))}>Previous</button><span>{offset+1}–{Math.min(offset+10,count)} of {count}</span><button disabled={offset+10>=count} onClick={()=>setOffset(n=>n+10)}>Next</button></nav></>:<p>You’re all caught up.</p>}{!!error&&<ErrorNotice error={error}/>}</Popover.Popup></Popover.Positioner></Popover.Portal></Popover.Root>;
}
