// Isolated production-component checks, not authenticated integration.
import {build} from 'esbuild';
import {createServer} from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';
const {chromium}=await import(pathToFileURL(process.env.BLOOM_PLAYWRIGHT ?? '/tmp/bloom-journey-browser-tools/node_modules/playwright/index.mjs').href);
const out='/tmp/bloom-payout-visual';await mkdir(out,{recursive:true});
await build({stdin:{contents:`import React from 'react';import {createRoot} from 'react-dom/client';import {AdminPayouts} from './src/components/bloom/admin-payouts';import './src/styles/bloom-owner.css';import './src/styles/bloom-application.css';createRoot(document.getElementById('root')).render(<main className="bloom-cleaner"><AdminPayouts/></main>);`,loader:'tsx',resolveDir:process.cwd()},bundle:true,outfile:`${out}/app.js`,platform:'browser',format:'esm',external:['/fonts/*'],jsx:'automatic',loader:{'.woff2':'dataurl','.svg':'dataurl'},plugins:[{name:'framework-only-stubs',setup(b){b.onResolve({filter:/^next\/(link|navigation)$/},args=>({path:args.path,namespace:'stub'}));b.onLoad({filter:/.*/,namespace:'stub'},()=>({contents:"import React from 'react';export default function Link(p){return React.createElement('a',p)};export const useRouter=()=>({push(){},refresh(){}});export const usePathname=()=>'/cleaner';export const useSearchParams=()=>new URLSearchParams('view=people');",loader:'js',resolveDir:process.cwd()}));}}]});
const server=createServer(async(req,res)=>{try{if(req.url.startsWith('/fonts/')){res.setHeader('Content-Type','font/ttf');res.end(await readFile(`public${req.url}`));}else if(req.url.startsWith('/app.')){res.setHeader('Content-Type',req.url.endsWith('.css')?'text/css':'text/javascript');res.end(await readFile(`${out}${req.url}`));}else{res.setHeader('Content-Type','text/html');res.end('<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/app.css"><div id="root"></div><script type="module" src="/app.js"></script>');}}catch{res.writeHead(404);res.end();}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const browser=await chromium.launch({headless:true,executablePath:process.env.BLOOM_CHROME ?? '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
const cleaning=(id,date,cents,extra={})=>({id,jobId:id,propertyName:'DEV FIXTURE · Repeat unit',cleaningDate:date,participation:'solo',originalEarningsCents:cents,adjustmentCents:0,paidCents:0,remainingCents:cents,status:'unpaid',reviewReason:null,comments:'DEV FIXTURE · Finished late; admin to review separately.',adjustments:[],...extra});
try{
 for(const width of [320,390,1440]){
  const page=await browser.newPage({viewport:{width,height:1000}});let posts=[];
  const person={id:'fixture-cleaner',name:'DEV FIXTURE Cleaner',preferredMethod:'Venmo',totalDueCents:10000,reviewCount:1};
  const detail={...person,cleanings:[cleaning('one','2025-01-01',7500),cleaning('two','2026-09-01',2500,{participation:'shared'}),cleaning('review','2024-01-01',null,{status:'review',reviewReason:'Missing finalized snapshot'})],payments:[{id:'prior',amountCents:1000,method:'PayPal',paymentDate:'2025-02-01',note:'DEV FIXTURE previous record',enteredBy:'Fixture Admin',createdAt:'2025-02-01T12:00:00Z',allocations:[{cleaningId:'one',amountCents:1000,propertyName:'DEV FIXTURE · Repeat unit',cleaningDate:'2025-01-01'}],voidedAt:null,voidedBy:null,voidReason:null}]};
  await page.route('**/api/admin/payouts**',async route=>{const req=route.request();if(req.method()==='POST'){posts.push({path:new URL(req.url()).pathname,body:req.postDataJSON(),key:req.headers()['idempotency-key']});await route.fulfill({json:{data:{ok:true}}});}else await route.fulfill({json:{data:new URL(req.url()).pathname.endsWith('/payouts')?{people:[person,{id:'zero',name:'No earnings',preferredMethod:null,totalDueCents:0,reviewCount:0}],totalOutstandingCents:10000,reviewCount:1,unassignedReviewCount:0}:detail}});});
  await page.goto('http://127.0.0.1:'+server.address().port);
  await page.getByRole('button',{name:person.name,exact:true}).waitFor();
  await page.getByLabel('Outstanding only').check();assert.equal(await page.getByRole('button',{name:'No earnings',exact:true}).count(),0);
  await page.getByLabel('Search cleaners').fill('missing');await page.getByText('No cleaners match these filters.').waitFor();await page.getByLabel('Search cleaners').fill('');
  await page.getByRole('button',{name:person.name,exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByRole('heading',{name:person.name}).waitFor();
  assert.equal(await dialog.locator('.payout-cleaning').count(),4);await dialog.getByText('Missing finalized snapshot').waitFor();
  const geometry=await dialog.evaluate(el=>({width:el.getBoundingClientRect().width,scroll:el.scrollWidth,client:el.clientWidth}));assert(geometry.width<=width);assert(geometry.scroll<=geometry.client+1);
  await dialog.getByRole('button',{name:'Record payment',exact:true}).click();
  await dialog.locator('.payout-form-grid summary').click();assert(await dialog.locator('.payout-form-grid table').isVisible());assert(await dialog.evaluate(el=>el.scrollWidth<=el.clientWidth+1));await dialog.locator('.payout-form-grid summary').click();
  await dialog.locator('.payout-allocation input[type=checkbox]').first().check();await dialog.getByLabel('Allocate for DEV FIXTURE · Repeat unit 2025-01-01').fill('25.00');await dialog.getByLabel('Payment amount (USD)').fill('30.00');await dialog.getByLabel('I confirm this payment').check();assert(await dialog.getByRole('button',{name:'Record external payment',exact:true}).isDisabled());await dialog.getByLabel('Payment amount (USD)').fill('25.00');
  assert.equal(await dialog.getByLabel('Actual payment method').inputValue(),'Venmo');await dialog.getByLabel('Actual payment method').selectOption('Cash');await dialog.getByRole('button',{name:'Record external payment',exact:true}).dblclick();await dialog.getByText('External payment recorded. No money was transferred by Bloom.').waitFor();assert.equal(posts.length,1);assert.equal(posts[0].body.amountCents,2500);assert.equal(posts[0].body.method,'Cash');assert.deepEqual(posts[0].body.allocations,[{cleaningId:'one',amountCents:2500}]);assert(posts[0].key);
  const first=dialog.getByRole('article',{name:'DEV FIXTURE · Repeat unit 2025-01-01',exact:true});await first.getByRole('button',{name:'Record adjustment',exact:true}).click();await first.getByLabel('Adjustment (USD)').fill('-5.00');assert(await first.getByRole('button',{name:'Record adjustment',exact:true}).isDisabled());await first.getByLabel('Reason (required)').fill('DEV FIXTURE agreed correction');await first.getByRole('button',{name:'Record adjustment',exact:true}).click();await dialog.getByText('Adjustment recorded. Original earnings are preserved.').waitFor();assert.equal(posts[1].body.amountCents,-500);
  const payment=dialog.getByRole('article',{name:'Payment 2025-02-01 prior',exact:true});await payment.getByRole('button',{name:'Correct / void record'}).click();assert(await payment.getByRole('button',{name:'Void payment record',exact:true}).isDisabled());await payment.getByLabel('Reason (required)').fill('DEV FIXTURE wrong reference');await payment.getByRole('button',{name:'Void payment record',exact:true}).click();await dialog.getByText('Payment voided. Its cleaning balances are available again. Record a replacement payment if needed.').waitFor();assert(posts[2].path.endsWith('/payments/prior/void'));assert.equal(posts[2].body.reason,'DEV FIXTURE wrong reference');
  await dialog.getByRole('button',{name:'Edit preferred method'}).click();await dialog.getByLabel('Method',{exact:true}).selectOption('Zelle');await dialog.getByRole('button',{name:'Save preferred method'}).click();await dialog.getByText('Preferred method saved. Past payments keep their recorded method.').waitFor();assert.equal(posts[3].body.method,'Zelle');
  const close=dialog.getByRole('button',{name:'Close details',exact:true});const box=await close.boundingBox(),db=await dialog.boundingBox();assert(box.x>db.x+db.width/2);await close.click();await dialog.waitFor({state:'hidden'});
  console.log(`PASS ${width}: all-time list, filtering, review, distinct repeat jobs, explicit partial allocations, confirmation, duplicate click, signed adjustment and dialog sizing.`);await page.close();
 }
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
