// Isolated production-component checks, not authenticated integration.
import {build} from 'esbuild';
import {createServer} from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';
const {chromium}=await import(pathToFileURL(process.env.BLOOM_PLAYWRIGHT ?? '/tmp/bloom-journey-browser-tools/node_modules/playwright/index.mjs').href);
const out='/tmp/bloom-picker-visual';await mkdir(out,{recursive:true});
await build({stdin:{contents:`import React,{useState} from 'react';import {createRoot} from 'react-dom/client';import {MonthHead} from './src/components/bloom/primitives';import {LocationDropdown} from './src/components/bloom/location-dropdown';import './src/styles/bloom-cleaner.css';import './src/styles/bloom-application.css';function App(){const[month,setMonth]=useState('2026-09');const[value,setValue]=useState('');return <main className="bloom-cleaner" style={{padding:24}}><h1>Jobs</h1><LocationDropdown locations={[{id:'',name:'All properties'},{id:'one',name:'Test property'}]} value={value} onValueChange={setValue} label="Filter jobs by property" searchLabel="Search properties"/><MonthHead month={month} onMonth={setMonth}/><button id="outside">Outside control</button></main>}createRoot(document.getElementById('root')).render(<App/>);`,loader:'tsx',resolveDir:process.cwd()},bundle:true,outfile:`${out}/app.js`,platform:'browser',format:'esm',external:['/fonts/*'],jsx:'automatic',loader:{'.woff2':'dataurl','.svg':'dataurl'},plugins:[{name:'framework-only-stubs',setup(b){b.onResolve({filter:/^next\/(link|navigation)$/},args=>({path:args.path,namespace:'stub'}));b.onLoad({filter:/.*/,namespace:'stub'},()=>({contents:"import React from 'react';export default function Link(p){return React.createElement('a',p)};export const useRouter=()=>({push(){},refresh(){}});export const usePathname=()=>'/cleaner';export const useSearchParams=()=>new URLSearchParams('view=people');",loader:'js',resolveDir:process.cwd()}));}}]});
const server=createServer(async(req,res)=>{try{if(req.url.startsWith('/fonts/')){res.setHeader('Content-Type','font/ttf');res.end(await readFile(`public${req.url}`));}else if(req.url.startsWith('/app.')){res.setHeader('Content-Type',req.url.endsWith('.css')?'text/css':'text/javascript');res.end(await readFile(`${out}${req.url}`));}else{res.setHeader('Content-Type','text/html');res.end('<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/app.css"><div id="root"></div><script type="module" src="/app.js"></script>');}}catch{res.writeHead(404);res.end();}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const browser=await chromium.launch({headless:true,executablePath:process.env.BLOOM_CHROME ?? '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
try{
 for(const width of [390,1440]){
  const page=await browser.newPage({viewport:{width,height:850}});await page.clock.setFixedTime(new Date('2026-09-22T16:00:00Z'));await page.goto('http://127.0.0.1:'+server.address().port);
  const filter=page.getByRole('button',{name:'Filter jobs by property: All properties'});await filter.click();await page.getByRole('menuitemradio',{name:'Test property'}).click();await page.getByRole('button',{name:'Filter jobs by property: Test property'}).waitFor();
  await page.getByRole('button',{name:'Filter jobs by property: Test property'}).click();await page.getByRole('menuitemradio',{name:'All properties',exact:true}).click();await filter.waitFor();
  await page.locator('.month-btn').click();await page.locator('.month-menu').waitFor();assert.equal(await page.locator('.month-menu [aria-selected="true"] button').textContent(),'22');assert.equal(await page.locator('.month-menu [aria-selected="true"] button').evaluate(el=>getComputedStyle(el).color),'rgb(255, 255, 255)');await page.getByRole('heading',{name:'Jobs'}).click();await page.locator('.month-menu').waitFor({state:'hidden'});
  await page.locator('.month-btn').click();await page.locator('.month-menu').waitFor();await page.keyboard.press('Escape');await page.locator('.month-menu').waitFor({state:'hidden'});assert(await page.locator('.month-btn').evaluate(el=>el===document.activeElement));
  await page.locator('.month-btn').click();await page.locator('.month-menu').waitFor();await page.locator('.month-select').dispatchEvent('pointerdown');await page.locator('.month-menu').waitFor({state:'hidden'});
  await page.locator('.month-btn').click();await page.locator('.month-menu').waitFor();await page.getByRole('heading',{name:'Jobs'}).dispatchEvent('click');await page.locator('.month-menu').waitFor({state:'hidden'});
  console.log('PASS '+width+': property dropdown selection/reset and shared calendar outside/Escape dismissal.');await page.close();
 }
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
