// Production component in browser with mocked API and OneSignal SDK. No provider sends.
import{build}from'esbuild';import{createServer}from'node:http';import{readFile,mkdir}from'node:fs/promises';import{pathToFileURL}from'node:url';import assert from'node:assert/strict';
const{chromium}=await import(pathToFileURL(process.env.BLOOM_PLAYWRIGHT??'.bloom-local/private/browser-tools/node_modules/playwright/index.mjs').href);const out='/tmp/bloom-push-ui';await mkdir(out,{recursive:true});
await build({stdin:{contents:`import React from 'react';import{createRoot}from'react-dom/client';import{PushSettings}from'./src/components/push/settings';import{NotificationInbox}from'./src/components/push/inbox';import './src/styles/bloom-application.css';createRoot(document.getElementById('root')).render(<><NotificationInbox cleaner/><PushSettings/></>);`,loader:'tsx',resolveDir:process.cwd()},bundle:true,outfile:out+'/app.js',platform:'browser',format:'esm',jsx:'automatic',external:['/fonts/*'],plugins:[{name:'next-stubs',setup(b){b.onResolve({filter:/^next\/(link|navigation)$/},x=>({path:x.path,namespace:'stub'}));b.onLoad({filter:/.*/,namespace:'stub'},()=>({contents:"import React from'react';export default p=>React.createElement('a',p);export const useRouter=()=>({});export const usePathname=()=>'/cleaner';export const useSearchParams=()=>new URLSearchParams();",resolveDir:process.cwd()}));}}]});
const server=createServer(async(req,res)=>{if(req.url.startsWith('/app.')){res.setHeader('Content-Type',req.url.endsWith('.js')?'text/javascript':'text/css');res.end(await readFile(out+req.url));}else{res.setHeader('Content-Type','text/html');res.end('<meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/app.css"><div id="root"></div><script type="module" src="/app.js"></script>');}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
try{for(const scenario of ['android','blocked','iphone','enabled']){
 const page=await browser.newPage({viewport:{width:390,height:844},...(scenario==='iphone'?{userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile Safari/604.1'}:{})});let settings={verified:scenario==='enabled',pending:false,newJobs:false,reminders:false,configured:true,appId:'synthetic'},challenge=0;let inboxItems=scenario==='enabled'?[{id:'push:synthetic',body:'2 cleanings available.',href:'/cleaner?view=calendar',dismissible:true}]:[];
 await page.addInitScript(({scenario})=>{window.promptCount=0;window.pushPermission=scenario==='blocked'?'denied':scenario==='enabled'?'granted':'default';Object.defineProperty(Notification,'permission',{get:()=>window.pushPermission});}, {scenario});
 await page.route('https://cdn.onesignal.com/**',r=>r.fulfill({contentType:'text/javascript',body:`const sdk={init:async()=>{},Notifications:{requestPermission:async()=>{window.promptCount++;window.pushPermission='granted';},isPushSupported:()=>true},User:{PushSubscription:{id:'00000000-0000-4000-8000-000000000001',optedIn:${scenario==='enabled'},optIn:async()=>{sdk.User.PushSubscription.optedIn=true},optOut:async()=>{sdk.User.PushSubscription.optedIn=false}}}};window.OneSignalDeferred.forEach(fn=>fn(sdk));`}));
 await page.route('**/api/**',async r=>{let data=settings;const path=new URL(r.request().url()).pathname;if(path==='/api/notifications'){if(r.request().method()==='POST')inboxItems=[];data={items:inboxItems,total:inboxItems.length};}else if(path==='/api/push/challenge'){challenge++;settings={...settings,pending:true};data={pending:true};}else if(r.request().method()==='POST'){settings={...settings,...r.request().postDataJSON()};data=settings;}await r.fulfill({json:{data}});});
 await page.goto('http://127.0.0.1:'+server.address().port);if(scenario==='enabled'){await page.waitForFunction(()=>document.querySelector('.bloom-push-card')?.hidden);await page.getByRole('button',{name:/^Notifications(?:,|$)/}).click();await page.getByText('2 cleanings available.').waitFor();await page.getByRole('button',{name:'Dismiss: 2 cleanings available.'}).click();await page.getByText('You’re all caught up.').waitFor();}await page.getByRole('button',{name:'Notification settings',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Job notification settings'});await dialog.waitFor();assert.equal(await page.evaluate(()=>window.promptCount),0);
 if(scenario==='android'){const enable=dialog.getByRole('button',{name:'Enable notifications',exact:true});await enable.click();await dialog.getByText('Tap the Bloom verification notification on this device to finish enabling.').waitFor();assert.equal(challenge,1);assert.equal(await page.evaluate(()=>window.promptCount),1);assert(await dialog.getByRole('button',{name:'Send test notification'}).isDisabled());await dialog.getByRole('checkbox',{name:'New available jobs in my approved city'}).click();await page.waitForFunction(()=>document.querySelector('input[type=checkbox]')?.checked);assert(settings.newJobs);}
 if(scenario==='blocked'){await dialog.getByText(/Notifications are blocked/).waitFor();assert.equal(await dialog.getByRole('button',{name:'Enable notifications',exact:true}).count(),0);}
 if(scenario==='iphone'){await dialog.getByRole('heading',{name:'Install Bloom on your iPhone'}).waitFor();assert.equal(await dialog.getByRole('button',{name:'Enable notifications',exact:true}).count(),0);}
 const box=await dialog.boundingBox();assert(box.width<=390&&box.height<=844);await page.keyboard.press('Escape');assert.equal(await page.getByRole('dialog',{name:'Job notification settings'}).count(),0);console.log('PASS mocked mobile '+scenario+': no automatic permission request, correct guidance/state, keyboard dismissal.');await page.close();
}}finally{await browser.close();await new Promise(r=>server.close(r));}
