'use client';
import {useCallback,useRef,useState} from 'react';
import Link from 'next/link';
import {Popover} from '@base-ui/react/popover';
import {request} from './api';
import {ErrorNotice,Loading,useResource} from './primitives';
import {parseSoloRate} from './property-form';
const dollars=(cents:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(cents/100);
export function AdminPricingInbox(){
 const load=useCallback((signal:AbortSignal)=>request<{id:string;name:string}[]>('/admin/pricing',{signal}),[]);
 const data=useResource(load);
 return <Popover.Root onOpenChange={open=>{if(open)data.reload();}}><Popover.Trigger className="admin-inbox-trigger" aria-label={`Notifications${data.data?.length?`, ${data.data.length} need attention`:''}`}><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></svg>{!!data.data?.length&&<span>{data.data.length}</span>}</Popover.Trigger><Popover.Portal><Popover.Positioner sideOffset={10} align="end" style={{zIndex:100}}><Popover.Popup className="admin-pricing-inbox"><Popover.Title>Notifications</Popover.Title>{data.loading?<Loading/>:data.error?<ErrorNotice error={data.error} retry={data.reload}/>:data.data?.length?<ul>{data.data.map(item=><li key={item.id}><Link href={`/admin?view=properties&property=${item.id}&section=settings`}>{item.name} needs cleaner pricing set<span>Set pricing →</span></Link></li>)}</ul>:<p>You’re all caught up.</p>}</Popover.Popup></Popover.Positioner></Popover.Portal></Popover.Root>;
}
export function AdminUnitPricing({id,onSaved}:{id:string;onSaved:()=>void}){
 const load=useCallback((signal:AbortSignal)=>request<{cents:number;configured:boolean}>(`/admin/properties/${id}/cleaner-pricing`,{signal}),[id]);const data=useResource(load);
 return data.loading?<Loading/>:data.error?<ErrorNotice error={data.error} retry={data.reload}/>:data.data?<AdminPricingEditor key={`${id}:${data.data.cents}:${data.data.configured}`} id={id} cents={data.data.cents} configured={data.data.configured} onSaved={()=>{data.reload();onSaved();}}/>:null;
}
export function AdminPricingEditor({id,cents,configured=true,version,onSaved}:{id:string;cents:number;configured?:boolean;version?:number;onSaved:()=>void}){
 const isJob=version!==undefined;const[value,setValue]=useState(configured?(cents/100).toFixed(2):'');const[reason,setReason]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState<unknown>();const[saved,setSaved]=useState(false);const lock=useRef(false);const receipt=useRef<{input:string;key:string}|null>(null);const next=parseSoloRate(value);
 return <section className="bloom-admin-card admin-cleaner-pricing"><h3>{isJob?'Cleaner payout':'Cleaner pricing'}</h3><p>{configured?`Solo ${dollars(cents)} · Shared ${dollars(cents/2)} per cleaner`:'Cleaner pricing needs to be set.'}</p><p>{isJob?'Override the total payout for this job. Two cleaners split it equally.':'Applies to future jobs and open, unassigned jobs. Assigned jobs keep their existing payout.'}</p><form className="bloom-form" onSubmit={async event=>{event.preventDefault();if(lock.current||next===null||next>100000000)return;lock.current=true;setBusy(true);setError(undefined);setSaved(false);const body=isJob?{cents:next,expectedVersion:version,reason:reason.trim()}:{cents:next};const input=JSON.stringify(body);if(receipt.current?.input!==input)receipt.current={input,key:crypto.randomUUID()};try{await request(isJob?`/admin/jobs/${id}/payout`:`/admin/properties/${id}/cleaner-pricing`,{body,key:receipt.current.key});setSaved(true);onSaved();}catch(error){setError(error);}finally{lock.current=false;setBusy(false);}}}><label>{isJob?'Total job payout (USD)':'Solo cleaner rate (USD)'}<input type="number" min="0.02" max="1000000" step="0.02" required disabled={busy} value={value} onChange={event=>setValue(event.target.value)}/></label>{next!==null&&<small>Shared: {dollars(next/2)} per cleaner</small>}{isJob&&<label>Reason for payout override<textarea required maxLength={1000} disabled={busy} value={reason} onChange={event=>setReason(event.target.value)}/></label>}<button className="bloom-button" disabled={busy||next===null||next>100000000||(isJob&&!reason.trim())}>{busy?'Saving…':isJob?'Override job payout':'Save cleaner pricing'}</button></form>{saved&&<p role="status">Saved.</p>}{!!error&&<ErrorNotice error={error}/>}</section>;
}
