'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import dynamic from 'next/dynamic';
import {request} from './api';
import {useResource} from './primitives';
import {validPin} from '../maps/points';
import type {CleanerJob} from '../../contracts';
import {formatDate,formatTime,money} from './dates';
import {Modal} from './primitives';

const JobMap=dynamic(()=>import('../maps/job-map'),{ssr:false,loading:()=> <p>Loading map…</p>});
export function CleanerDayDialog({date,jobs,onSelect,onClose}:{date:string;jobs:CleanerJob[];onSelect:(job:CleanerJob)=>void;onClose:()=>void}){
 const dayJobs=useMemo(()=>jobs.filter(job=>job.checkoutDate===date),[jobs,date]);
 const [hovered,setHovered]=useState<string|null>(null);
 const [highlight,setHighlight]=useState<string|null>(null),[view,setView]=useState<'list'|'map'>('list'),[mapNeeded,setMapNeeded]=useState(false);
 const load=useCallback((signal:AbortSignal)=>request<{jobId:string;latitude:number;longitude:number}[]>(`/jobs/pins?date=${date}`,{signal}),[date]);const pins=useResource(load);
 const points=useMemo(()=>dayJobs.flatMap(job=>{const pin=pins.data?.find(p=>p.jobId===job.id);return pin&&validPin(pin)?[{id:job.id,label:job.propertyName,latitude:pin.latitude,longitude:pin.longitude}]:[];}),[dayJobs,pins.data]);
 useEffect(()=>{const media=matchMedia('(min-width: 761px)');const check=()=>{if(media.matches)setMapNeeded(true);};check();media.addEventListener('change',check);return()=>media.removeEventListener('change',check);},[]);
 function select(id:string){setHighlight(id);document.getElementById(`day-job-${id}`)?.scrollIntoView({block:'nearest',behavior:'smooth'});}
 return <Modal className="cleaner-day-dialog" title={`Cleanings for ${formatDate(date)}`} onClose={onClose}><header><p className="cleaner-day-eyebrow">Your cleaning calendar</p><h2>{formatDate(date)}</h2><p>{dayJobs.length} {dayJobs.length===1?'cleaning':'cleanings'} · Times are local to each property</p></header><div className="cleaner-day-toggle" role="group" aria-label="Day view"><button aria-pressed={view==='list'} onClick={()=>setView('list')}>List</button><button aria-pressed={view==='map'} onClick={()=>{setView('map');setMapNeeded(true);}}>Map</button></div><div className={`cleaner-day-columns day-view-${view}`}><div className="cleaner-day-list">{dayJobs.length?<ul className="cleaner-day-jobs">{[...dayJobs].sort((a,b)=>a.startAt.localeCompare(b.startAt)||a.propertyName.localeCompare(b.propertyName)).map(job=><li id={`day-job-${job.id}`} key={job.id} onMouseEnter={()=>setHovered(job.id)} onMouseLeave={()=>setHovered(null)} onFocus={()=>setHovered(job.id)} onBlur={()=>setHovered(null)} className={highlight===job.id?'selected':''}><button type="button" aria-pressed={highlight===job.id} onClick={()=>select(job.id)}><span className="cleaner-day-card-heading"><strong>{job.propertyName}</strong><span className="cleaner-day-badges"><span className="cleaner-day-count" data-count={job.activeCleanerCount}>{job.activeCleanerCount}/2 cleaners</span><span className="cleaner-day-status" data-status={job.status}>{job.status==='completed'?'Completed':job.status==='cancelled'?'Cancelled':'Open'}</span></span></span><span>{formatTime(job.startAt,job.timezone)}–{formatTime(job.endAt,job.timezone)} · {job.timezone}</span><span>{money(job.soloRateCents)} solo · {money(job.sharedRateCents)} shared</span>{job.myAssignmentId&&<span className="cleaner-day-assigned">You’re assigned</span>}{job.reviewRequired&&<span>Booking changes need admin attention</span>}<span>{pins.loading?'Checking location…':points.some(p=>p.id===job.id)?'Show on map':'Location unavailable'}</span></button><button type="button" className="cleaner-day-link" onClick={()=>onSelect(job)}>View cleaning →</button></li>)}</ul>:<p className="cleaner-day-empty">No cleanings for this day with your current filters.</p>}</div><div className="cleaner-day-map">{pins.error?<p role="status">Locations could not load. You can still use the list. <button onClick={pins.reload}>Retry locations</button></p>:pins.loading?<p>Loading locations…</p>:points.length?mapNeeded&&<JobMap points={points} selected={hovered??highlight} onSelect={select}/>:<p>Location unavailable. No confirmed property pins for these cleanings.</p>}</div></div></Modal>;
}
