 'use client';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxEmpty,ComboboxList,ComboboxItem,ComboboxChips,ComboboxChip,ComboboxValue,ComboboxGroup,ComboboxLabel,ComboboxCollection,ComboboxSeparator} from '../ui/combobox';
type Unit={value:string;label:string};
export function OwnerUnitFilter({properties,hidden,onChange}:{properties:{id:string;name:string;cityId?:string|null;cityName?:string|null}[];hidden:string[];onChange:(hidden:string[])=>void}) {
 const groups:Array<{value:string;label:string;items:Unit[]}>=[];
 for(const p of properties){const key=p.cityId??'unknown';let group=groups.find(g=>g.value===key);if(!group){group={value:key,label:p.cityName??'City unavailable',items:[]};groups.push(group);}group.items.push({value:p.id,label:p.name});}
 groups.sort((a,b)=>a.label.localeCompare(b.label));
 const selected=groups.flatMap(g=>g.items).filter(p=>!hidden.includes(p.value));
 return <div className="owner-unit-filter"><Combobox multiple items={groups} value={selected} itemToStringLabel={(item:Unit)=>item.label} isItemEqualToValue={(a:Unit,b:Unit)=>a.value===b.value} onValueChange={values=>onChange(properties.filter(p=>!values.some(value=>value.value===p.id)).map(p=>p.id))}><ComboboxInput placeholder="Search and select units" aria-label="Search and select units" showClear hasSelection={selected.length>0}><ComboboxChips><ComboboxValue>{(values:Unit[])=><>{values.slice(0,2).map(item=><ComboboxChip key={item.value}>{item.label}</ComboboxChip>)}{values.length>2&&<span className="owner-chip-overflow">+{values.length-2} more</span>}</>}</ComboboxValue></ComboboxChips></ComboboxInput><ComboboxContent><button type="button" className="owner-select-all" onClick={()=>onChange([])}>Select all units</button><ComboboxEmpty>No units found.</ComboboxEmpty><ComboboxList>{(group,index)=><ComboboxGroup key={group.value} items={group.items}><ComboboxLabel>{group.label}</ComboboxLabel><ComboboxCollection>{(item:Unit)=><ComboboxItem key={item.value} value={item}>{item.label}</ComboboxItem>}</ComboboxCollection>{index<groups.length-1&&<ComboboxSeparator/>}</ComboboxGroup>}</ComboboxList></ComboboxContent></Combobox><span className="owner-unit-count" role="status">{selected.length} of {properties.length} units selected</span></div>;
}
