'use client';
import {PropertyAvatars,PropertyPeoplePanel} from './property-people';
import { useCallback, useRef, useState, type ReactNode } from 'react';
import type { OwnerListing, OwnerSource, OwnerPerformance } from '../../contracts/owner-hub';
import type { SyncResult } from '../../contracts';
import type { BloomIntegration } from './integration';
import { ApiError, request } from './api';
import { Empty, ErrorNotice, Icon, Loading, useResource } from './primitives';
import { PropertyName } from './property-name';
import { CalendarSetupCard } from './supply-setup-grid';
import { CleaningConfiguration } from './cleaning-config';
import { MaintenanceGrid as OwnerMaintenance } from './maintenance';
import { PropertyDelete } from './property-delete';
import { occupancyLabel } from './owner-utils';

const supplyLabels={full:'Full',moderate:'Moderate',low:'Low',empty:'Empty',not_found:'Not found'};
export function OwnerSupplySummary({listing}:{listing:OwnerListing}){
 return <><h3>Supplies</h3>{listing.suppliesUnavailable?<p>Supply reports are not available in the admin Owner Hub view yet.</p>:!listing.supplies.length?<p>No supplies are configured for this unit yet.</p>:<><p>Last cleaner-reported levels · Read-only</p><div className="owner-supply-grid">{listing.supplies.map(supply=><article className="owner-supply-card" key={supply.supplyId} data-level={supply.level??'unknown'}><svg width="28" height="32" viewBox="0 0 28 32" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><path d="M10 3h8v5l4 5v15H6V13l4-5V3ZM10 8h8M6 18h16M18 3h5"/></svg><strong>{supply.name}</strong><span>{supply.level===null?'Not reported yet':supplyLabels[supply.level]}</span><div className="owner-supply-bar" aria-hidden="true"><span/></div><small>{supply.reportedAt?`Last reported ${new Intl.DateTimeFormat('en-US',{dateStyle:'medium',timeStyle:'short',timeZone:listing.timezone}).format(new Date(supply.reportedAt))} (${listing.timezone})`:'No completed cleaning report yet'}</small></article>)}</div></>}</>;

}
export function OwnerSources({listing,onChanged}:{listing:OwnerListing;onChanged:()=>void}){
 const [provider,setProvider]=useState<'airbnb'|'vrbo'>('airbnb');
 const [addConflict,setAddConflict]=useState(false);
 const [url,setUrl]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState<unknown>();const [result,setResult]=useState('');
 const lock=useRef(false);const receipt=useRef<{input:string;key:string}|null>(null);
 async function mutate(action:'add'|'sync',source?:OwnerSource){
  if(lock.current)return;lock.current=true;setBusy(true);setError(undefined);setAddConflict(false);setResult('');
  const input=JSON.stringify({action,propertyId:listing.id,sourceId:source?.id,provider,url:action==='add'?url:undefined});
  if(receipt.current?.input!==input)receipt.current={input,key:crypto.randomUUID()};
  try{
   const path=`/owner/properties/${encodeURIComponent(listing.id)}/calendar-sources`;
   if(action==='add'){await request<OwnerSource>(path,{body:provider==='airbnb'?{url}:{url,provider},key:receipt.current.key});setUrl('');setResult(`${provider==='airbnb'?'Airbnb':'Vrbo'} link saved. Choose Sync now to import its calendar.`);}
   else{const synced=await request<SyncResult&{status:'success'|'partial'|'not_modified'}>(`${path}/${encodeURIComponent(source!.id)}/sync`,{body:{},key:receipt.current.key});setResult(synced.status==='partial'?'The export was incomplete. Existing stays were preserved; check source status.':synced.status==='not_modified'?'Calendar unchanged.':`Synced calendar entries: ${synced.created} added, ${synced.updated} updated, ${synced.removed} removed. These counts describe calendar entries.`);}
   receipt.current=null;onChanged();
  }catch(failure){setError(failure);setAddConflict(action==='add'&&failure instanceof ApiError&&failure.code==='CONFLICT');if(failure instanceof ApiError&&!['NETWORK_ERROR','SOURCE_UNAVAILABLE','SERVICE_UNAVAILABLE'].includes(failure.code))receipt.current=null;}
  finally{lock.current=false;setBusy(false);}
 }
 return <section aria-label={`${listing.name} calendar connection`}><h3>Calendar connection</h3>{listing.sources.length?listing.sources.map(source=><div className="owner-source" key={source.id}><strong>{source.provider==='airbnb'?'Airbnb':'Vrbo'}</strong><p>{source.enabled?'Enabled':'Disabled'} · Last successful sync: {source.lastSuccessAt?new Intl.DateTimeFormat('en-US',{dateStyle:'medium',timeStyle:'short',timeZone:listing.timezone}).format(new Date(source.lastSuccessAt)):'Not yet synced'}</p>{source.message&&<p className="bloom-notice">{source.message}</p>}{<button type="button" className="bloom-button secondary" disabled={busy||!source.enabled} onClick={()=>void mutate('sync',source)}>{busy?'Working…':'Sync now'}</button>}</div>):<p>No calendar sources connected.</p>}
 <form className="bloom-form" onSubmit={event=>{event.preventDefault();void mutate('add');}}><CalendarSetupCard provider={provider} url={url} onProvider={setProvider} onUrl={setUrl} required disabled={busy}/><p>Use the provider’s calendar export link (iCal) from availability settings, not the public listing URL. This link connects only to {listing.name}. It is stored privately and never displayed in the source list. Saving a link does not import stays until you sync. If sync fails, the listing stays saved; retry the sync.</p><button className="bloom-button" disabled={busy||!url.trim()}>{busy?'Working…':provider==='airbnb'?'Connect Airbnb calendar':'Connect Vrbo calendar'}</button></form>{!!error&&<ErrorNotice error={error}/>} {addConflict&&<p className="bloom-notice">The calendar connection could not be updated. Refresh the listing and check its saved calendars before retrying.</p>}<p role="status">{result}</p></section>;
}

function OwnerPlatformShare({id,from,toExclusive,revision}:{id:string;from:string;toExclusive:string;revision:number}) {
 const load=useCallback((signal:AbortSignal)=>request<OwnerPerformance>(`/owner/performance?${new URLSearchParams({from,toExclusive,propertyId:id})}`,{signal}),[id,from,toExclusive,revision]);
 const data=useResource(load);
 return <section aria-label="Listing platform share"><h3>Platform share</h3><p>{from} to {toExclusive} (end exclusive) · Based on known occupied nights</p>{data.loading?<Loading/>:data.error?<ErrorNotice error={data.error} retry={data.reload}/>:data.data&&<>{data.data.totals.coverage.status!=='complete'&&<p>{data.data.totals.coverage.message}</p>}{data.data.totals.occupiedNights===0?<p>N/A — no occupied-night data in this range.</p>:<ul className="owner-share">{(['airbnb','vrbo','unknown'] as const).map(platform=>{const entry=data.data!.totals.platformShare.find(p=>p.platform===platform);return <li key={platform}>{platform==='airbnb'?'Airbnb':platform==='vrbo'?'Vrbo':'Off-platform / unknown'}: {entry?.share==null?'N/A':occupancyLabel(entry.share)}</li>;})}</ul>}</>}</section>;
}
function OwnerListingDetails({listing,integration,onChanged,from,toExclusive,revision,demo=false,settingsContent}:{listing:OwnerListing;integration:BloomIntegration;onChanged:()=>void;from:string;toExclusive:string;revision:number;demo?:boolean;settingsContent?:ReactNode}) {
 const [showDemo,setShowDemo]=useState(true);
 const [slide,setSlide]=useState(0);const names=['Rate','Supplies','Maintenance','Settings'];
 return <article className="owner-listing-detail" aria-label={`${listing.name} details`}><h2>{listing.name}</h2><p>{listing.active?'Active':'Inactive'} · {listing.timezone}</p><div className="owner-detail-navigation"><div className="view-toggle" role="group" aria-label="Property information">{names.map((name,index)=><button key={name} className={`vt-btn${slide===index?' active':''}`} aria-pressed={slide===index} onClick={()=>setSlide(index)}>{name}</button>)}</div><div className="owner-carousel-controls"><button className="icon-btn" aria-label="Previous property section" onClick={()=>setSlide((slide+3)%4)}><Icon name="left"/></button><button className="icon-btn" aria-label="Next property section" onClick={()=>setSlide((slide+1)%4)}><Icon name="right"/></button></div></div><div role="region" aria-roledescription="carousel" aria-label="Property details"><div hidden={slide!==0} role="group" aria-label="Rate, 1 of 4"><h3>Rate</h3><div className="owner-rate-card"><p>Nightly guest rate</p><strong>N/A</strong><p>Host payout: N/A</p><small>Price updates coming soon.</small></div><OwnerPlatformShare id={listing.id} from={from} toExclusive={toExclusive} revision={revision}/></div><div hidden={slide!==1} role="group" aria-label="Supplies, 2 of 4"><OwnerSupplySummary listing={listing}/>{demo&&<aside className="owner-supply-demo"><div className="owner-settings-heading"><h3>Demo supplies · Not saved</h3><button className="bloom-button secondary" onClick={()=>setShowDemo(!showDemo)}>{showDemo?'Hide preview':'Show preview'}</button></div><p>Development preview only. These are sample levels, separate from this property's reports.</p>{showDemo&&<OwnerSupplySummary listing={{...listing,suppliesUnavailable:false,supplies:[{supplyId:'demo-soap',name:'Dish soap',level:'full',reportedAt:null},{supplyId:'demo-spray',name:'All-purpose cleaner',level:'moderate',reportedAt:null},{supplyId:'demo-paper',name:'Paper towels',level:'low',reportedAt:null},{supplyId:'demo-bags',name:'Trash bags',level:'empty',reportedAt:null},{supplyId:'demo-glass',name:'Window cleaner',level:'not_found',reportedAt:null}]}}/>}</aside>}</div><div hidden={slide!==2} role="group" aria-label="Maintenance, 3 of 4"><OwnerMaintenance reports={listing.maintenance}/></div><div hidden={slide!==3} role="group" aria-label="Settings, 4 of 4">{settingsContent??<><div className="owner-settings-heading"><h3>Settings</h3><PropertyName property={listing} rename={integration.renameProperty} onSaved={onChanged}/></div>{listing.setupRequired&&<p className="bloom-notice">Finish your rooms and supplies below to make cleaning jobs available.</p>}<CleaningConfiguration propertyId={listing.id} owner bedroomCount={listing.bedroomCount} bathroomCount={listing.bathroomCount} onSaved={onChanged} calendar={<OwnerSources listing={listing} onChanged={onChanged}/>} people={<PropertyPeoplePanel listing={listing}/>}/></>}</div></div></article>;
}
export function OwnerListings({listings,integration,onChanged,from,toExclusive,revision,addListingAction,initialSelectedId,renderSettings}:{listings:OwnerListing[];integration:BloomIntegration;onChanged:()=>void;from:string;toExclusive:string;revision:number;addListingAction?:ReactNode;initialSelectedId?:string;renderSettings?:(listing:OwnerListing)=>ReactNode}){
 const [selectedId,setSelectedId]=useState<string|null>(initialSelectedId??null);
 const selected=listings.find(p=>p.id===selectedId)??listings[0];
 return <section className="owner-listings-section" aria-label="Your listings"><div className="loc-header"><h2>Listings</h2>{addListingAction}</div>{!selected?<Empty title="No properties yet">Add a listing to get started.</Empty>:<div className="owner-listings-split"><nav className="owner-listings-rail" aria-label="Properties">{listings.map(listing=><div key={listing.id} className="owner-property-card-wrap"><button className={`owner-property-card${listing.id===selected.id?' active':''}`} aria-pressed={listing.id===selected.id} onClick={()=>setSelectedId(listing.id)}><Icon name="pin" size={24}/><strong>{listing.name}</strong><span className="property-card-footer"><span>{listing.cityName??listing.timezone}</span><PropertyAvatars propertyId={listing.id}/></span></button><PropertyDelete property={listing} onDeleted={onChanged} iconOnly/></div>)}</nav><OwnerListingDetails settingsContent={renderSettings?.(selected)} key={selected.id} demo={process.env.NODE_ENV==='development'&&listings.slice(0,2).some(p=>p.id===selected.id)} listing={selected} integration={integration} onChanged={onChanged} from={from} toExclusive={toExclusive} revision={revision}/></div>}</section>;
}
