'use client';
import {useCallback,useState} from 'react';
import dynamic from 'next/dynamic';
import {request} from './api';
import {ErrorNotice,Loading,useResource} from './primitives';
import {AddressPinPicker} from '../maps/address-pin';
import {validPin} from '../maps/points';
const JobMap=dynamic(()=>import('../maps/job-map'),{ssr:false});
type Pin={latitude:number;longitude:number};
export function PropertyPin({id,address}:{id:string;address:string}){const load=useCallback((signal:AbortSignal)=>request<Pin|null>(`/admin/properties/${id}/pin`,{signal}),[id]);const data=useResource(load);return <section className="bloom-admin-card"><h2>Property map pin</h2><p>Find the saved address on the map, or enter verified coordinates. Confirm the pin before saving.</p>{data.loading?<Loading/>:data.error?<ErrorNotice error={data.error} retry={data.reload}/>:<PinEditor key={JSON.stringify(data.data)} id={id} address={address} initial={data.data??null} saved={data.reload}/>}</section>;}
function PinEditor({id,address,initial,saved}:{id:string;address:string;initial:Pin|null;saved:()=>void}){const [lat,setLat]=useState(initial?.latitude.toString()??''),[lng,setLng]=useState(initial?.longitude.toString()??''),[preview,setPreview]=useState<Pin|null>(null),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>();const pin={latitude:Number(lat),longitude:Number(lng)};const valid=!!lat.trim()&&!!lng.trim()&&validPin(pin);return <form className="bloom-form" onSubmit={async e=>{e.preventDefault();if(busy||!valid||!confirmed)return;setBusy(true);setError(undefined);try{await request(`/admin/properties/${id}/pin`,{body:{...pin,confirmed:true}});saved();}catch(e){setError(e);}finally{setBusy(false);}}}><AddressPinPicker showPreview={false} key={address} address={address} value={preview?{...preview,address,label:address}:null} onChange={pin=>{setLat(pin?.latitude.toString()??'');setLng(pin?.longitude.toString()??'');setPreview(pin);setConfirmed(false);}}/><SuggestedPin id={id} usePin={pin=>{setLat(String(pin.latitude));setLng(String(pin.longitude));setPreview(pin);setConfirmed(false);}}/><label>Latitude<input inputMode="decimal" value={lat} onChange={e=>{setLat(e.target.value);setPreview(null);setConfirmed(false);}}/></label><label>Longitude<input inputMode="decimal" value={lng} onChange={e=>{setLng(e.target.value);setPreview(null);setConfirmed(false);}}/></label><button type="button" className="bloom-button secondary" disabled={!valid} onClick={()=>setPreview(pin)}>Preview pin</button>{preview&&<JobMap points={[{...preview,id,label:'Property pin'}]} selected={id} onSelect={()=>{}} locate={false}/>}<label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I confirm these coordinates mark the correct property.</label><button className="bloom-button" disabled={busy||!valid||!confirmed}>{busy?'Saving…':'Save confirmed pin'}</button>{initial&&<p>Confirmed pin saved.</p>}{!!error&&<ErrorNotice error={error}/>}</form>;}

function SuggestedPin({id,usePin}:{id:string;usePin:(pin:Pin)=>void}){const load=useCallback((signal:AbortSignal)=>request<Pin|null>(`/owner/properties/${id}/pin-suggestion`,{signal}),[id]);const data=useResource(load);return data.error?<ErrorNotice error={data.error} retry={data.reload}/>:data.data?<div><p>An owner submitted a location for review.</p><button type="button" className="bloom-button secondary" onClick={()=>usePin(data.data!)}>Preview owner's suggested pin</button></div>:null;}
