'use client';
import {useCallback,useRef,useState} from 'react';
import type {PropertyPeople,IncomingPropertyInvitation} from '../../contracts/property-people';
import {ResendInvite} from './pending-invitations';
import {PeoplePage} from './people-page';
import {request,ApiError} from './api';
import {ErrorNotice,Loading,useResource} from './primitives';

type Listing={id:string;name:string};
export function PropertyAvatars({propertyId}:{propertyId:string}){
 const load=useCallback((signal:AbortSignal)=>request<PropertyPeople>(`/properties/${propertyId}/people`,{signal}),[propertyId]);const data=useResource(load);
 if(!data.data)return null;
 return <PropertyAvatarStack bloomOwned={data.data.bloomOwned} members={data.data.members}/>;
}
export function PropertyAvatarStack({bloomOwned,members}:Pick<PropertyPeople,'bloomOwned'|'members'>){
 return <span className="property-avatars" aria-label={bloomOwned?'Bloom-owned':`${members.length} owners`}>
 {bloomOwned?<img src="/icon.svg" alt="Bloom" width={30} height={30}/>:<>{members.slice(0,2).map(member=><span className="property-avatar" key={member.id} title={member.displayName}>{member.imageUrl?<img src={member.imageUrl} alt={member.displayName} width={30} height={30} referrerPolicy="no-referrer"/>:<span aria-label={member.displayName}>{member.displayName.slice(0,1)}</span>}</span>)}{members.length>2&&<span className="property-avatar property-avatar-count">+{members.length-2}</span>}</>}
 </span>;
}
export function PropertyPeoplePanel({listing,showInvite=true}:{listing:Listing;showInvite?:boolean}){
 const load=useCallback((signal:AbortSignal)=>request<PropertyPeople>(`/properties/${listing.id}/people`,{signal}),[listing.id]);const data=useResource(load);
 return <section aria-label={`${listing.name} people`}><h3>People</h3><p>Co-owners can view and manage this property, including its settings and invitations.</p>{showInvite&&<PropertyInviteForm listings={[listing]} fixedPropertyId={listing.id} onSent={data.reload}/>}{data.loading?<Loading/>:data.error?<ErrorNotice error={data.error} retry={data.reload}/>:data.data&&<><h4>Owners</h4>{data.data.bloomOwned&&<p>Bloom-owned</p>}{data.data.members.length?<PeoplePage items={data.data.members} label="Owners">{members=><div className="admin-people-table-scroll"><table className="admin-people-table owner-people-table"><thead><tr><th scope="col">Name</th><th scope="col">Role</th><th scope="col">Location</th></tr></thead><tbody>{members.map(member=><tr key={member.id}><th scope="row"><span className="owner-person-name">{member.imageUrl&&<img src={member.imageUrl} alt="" width={32} height={32} referrerPolicy="no-referrer"/>}{member.displayName}</span></th><td>Owner</td><td>{member.location??'—'}</td></tr>)}</tbody></table></div>}</PeoplePage>:<p>No individual owners associated.</p>}<h4>Invitations</h4>{data.data.invitations.length?<PeoplePage items={data.data.invitations} label="Invitations">{invitations=><div className="admin-people-table-scroll"><table className="admin-people-table owner-people-table"><thead><tr><th scope="col">Email</th><th scope="col">Status</th><th scope="col">Expires</th><th scope="col">Action</th></tr></thead><tbody>{invitations.map(invite=><tr key={invite.id}><td>{invite.email}{['pending','sent'].includes(invite.status)&&<span className="bloom-pending-label">Pending</span>}</td><td>{invite.status==='pending'?'Delivery not confirmed — retry sending':invite.status}</td><td>{invite.status==='accepted'?'—':new Date(invite.expiresAt).toLocaleDateString()}</td><td>{['pending','sent'].includes(invite.status)&&new Date(invite.expiresAt).getTime()>Date.now()&&<ResendInvite email={invite.email} path={`/properties/${listing.id}/people`} onSent={()=>{}}/>}</td></tr>)}</tbody></table></div>}</PeoplePage>:<p>No invitations yet.</p>}</>}</section>;
}
function PropertyInviteForm({listings,fixedPropertyId,onSent}:{listings:Listing[];fixedPropertyId?:string;onSent?:()=>void}){
 const[email,setEmail]=useState(''),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState<unknown>();
 const lock=useRef(false),receipt=useRef<{input:string;key:string}|null>(null);const propertyId=fixedPropertyId??selected;
 return <form className="bloom-admin-card bloom-form property-invite-form" onSubmit={async event=>{event.preventDefault();if(lock.current||!propertyId)return;lock.current=true;setBusy(true);setError(undefined);setMessage('');const body={email:email.trim().toLowerCase()},input=JSON.stringify({propertyId,...body});if(receipt.current?.input!==input)receipt.current={input,key:crypto.randomUUID()};try{const result=await request<{status:string}>(`/properties/${propertyId}/people`,{body,key:receipt.current.key});setMessage(result.status==='accepted'?'This invitation has already been accepted.':'Invitation sent. Property access begins after acceptance.');setEmail('');receipt.current=null;onSent?.();}catch(failure){setError(failure);}finally{lock.current=false;setBusy(false);}}}>
 <h3>Invite a co-owner</h3><div className="admin-invite-fields"><label>Email address<input type="email" required maxLength={254} disabled={busy} autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@example.com"/></label>{fixedPropertyId?<p className="property-invite-context">Property: {listings.find(p=>p.id===fixedPropertyId)?.name}</p>:<label>Property<select aria-label="Invitation property" required disabled={busy} value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose a property</option>{listings.map(listing=><option key={listing.id} value={listing.id}>{listing.name}</option>)}</select></label>}<button className="bloom-button" disabled={busy||!email.trim()||!propertyId}>{busy?'Sending…':'Send invite'}</button></div>
 {!!error&&!(error instanceof ApiError&&error.code==='SOURCE_UNAVAILABLE')&&<ErrorNotice error={error}/>} {error instanceof ApiError&&error.code==='CONFLICT'&&<p>An invitation may still be sending. Wait two minutes, then retry with the same email and property.</p>} {error instanceof ApiError&&error.code==='SOURCE_UNAVAILABLE'&&<p>Delivery could not be confirmed. Your inputs are saved here; wait two minutes before retrying.</p>}{message&&<p role="status">{message}</p>}</form>;
}
export function OwnerPeople({listings}:{listings:Listing[]}){
 const[selected,setSelected]=useState(listings[0]?.id??'');const[revision,setRevision]=useState(0);return <section className="owner-people-page"><h2>People</h2><IncomingInvitations/>{listings.length?<><PropertyInviteForm listings={listings} onSent={()=>setRevision(value=>value+1)}/><label className="property-owner-picker"><span>Manage property owners</span><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose a property</option>{listings.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label>{selected&&listings.some(p=>p.id===selected)&&<PropertyPeoplePanel showInvite={false} key={`${selected}:${revision}`} listing={listings.find(p=>p.id===selected)!}/>}</>:<p>Add a listing before inviting co-owners.</p>}</section>;
}
export function IncomingInvitations(){
 const load=useCallback((signal:AbortSignal)=>request<IncomingPropertyInvitation[]>('/property-invitations',{signal}),[]);const data=useResource(load);const[busy,setBusy]=useState<string|null>(null),[error,setError]=useState<unknown>();const lock=useRef(false),keys=useRef(new Map<string,string>());
 return <section aria-label="Invitations for you"><h3>Invitations for you</h3>{data.loading?<Loading/>:data.error?<ErrorNotice error={data.error} retry={data.reload}/>:data.data?.length?<ul className="property-people-list">{data.data.map(invite=><li key={invite.id}><div><strong>{invite.propertyName}</strong><p>Invited by {invite.inviterName}. Accepting gives you co-owner access to this property.</p><button className="bloom-button" disabled={busy!==null} onClick={async()=>{if(lock.current)return;lock.current=true;setBusy(invite.id);setError(undefined);if(!keys.current.has(invite.id))keys.current.set(invite.id,crypto.randomUUID());try{const result=await request<{role:string}>(`/property-invitations/${invite.id}/accept`,{body:{},key:keys.current.get(invite.id)!});window.location.assign(result.role==='admin'?'/admin':'/owner');}catch(failure){setError(failure);}finally{lock.current=false;setBusy(null);}}}>{busy===invite.id?'Accepting…':'Accept invitation'}</button></div></li>)}</ul>:<p>No pending invitations for your verified email addresses.</p>}{!!error&&<ErrorNotice error={error}/>} {error instanceof ApiError&&error.code==='FORBIDDEN'&&<p>This account has a different Bloom role. Ask an admin to review it; accepting an invitation cannot change your role.</p>}</section>;
}
