'use client';
import type { CleaningConfig } from '../../contracts';
export function SupplyIcon(){return <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><path d="M9 3h6v4H9zM8 7h8l2 5v9H6v-9zM6 14h12"/></svg>;}
/** Shared by initial listing setup and persisted property settings. */
export function SupplySetupGrid({supplies,onChange,disabled=false,optional=false}:{supplies:CleaningConfig['supplies'];onChange:(supplies:CleaningConfig['supplies'])=>void;disabled?:boolean;optional?:boolean}){
 return <fieldset disabled={disabled}><legend>Supplies (optional)</legend><p>Add the supplies cleaners should report. {optional?'You can skip this and add them later in Settings.':'Save an empty list if this property needs no supply checklist.'}</p><div className="owner-create-supply-grid">{supplies.map((supply,index)=><div className="owner-room-count-card" key={supply.id}><SupplyIcon/><label>Supply {index+1}<input aria-label={`Supply ${index+1}`} required={!optional} maxLength={100} placeholder="e.g. Dish soap" value={supply.name} onChange={event=>onChange(supplies.map(s=>s.id===supply.id?{...s,name:event.target.value}:s))}/></label><button type="button" className="bloom-button secondary" aria-label={`Remove supply ${index+1}`} onClick={()=>onChange(supplies.filter(s=>s.id!==supply.id))}>Remove</button></div>)}</div><button type="button" className="bloom-button secondary" disabled={supplies.length>=100} onClick={()=>onChange([...supplies,{id:crypto.randomUUID(),name:''}])}>+ Add supply</button></fieldset>;
}
export function CalendarSetupCard({provider,url,onProvider,onUrl,disabled=false,required=false,title,remove}:{provider:'airbnb'|'vrbo';url:string;onProvider:(provider:'airbnb'|'vrbo')=>void;onUrl:(url:string)=>void;disabled?:boolean;required?:boolean;title?:string;remove?:()=>void}){
 return <div className="owner-room-count-card owner-calendar-setup-card">{title&&<strong>{title}</strong>}<label>Calendar provider<select disabled={disabled} value={provider} onChange={e=>onProvider(e.target.value as 'airbnb'|'vrbo')}><option value="airbnb">Airbnb</option><option value="vrbo">Vrbo</option></select></label><label>Private {provider==='airbnb'?'Airbnb':'Vrbo'} iCal export link<input type="password" required={required} disabled={disabled} maxLength={4096} autoComplete="off" value={url} onChange={e=>onUrl(e.target.value)}/></label>{remove&&<button type="button" className="bloom-button secondary" disabled={disabled} aria-label={`Remove ${title?.toLowerCase()??'calendar'}`} onClick={remove}>Remove</button>}</div>;
}
